### ISSUE TITLE
Word distance needs some tweak

### ISSUE THREAD

**Issue by JulianJason** [JulianJason/The-Travelling-Man#10]
In WordDistance.java, I changed @MatthewNeo's Algo to do it word by word so that it could capture Sentozza to sentosa.

However, running the itinerary planner through the word distance function causes it to go through all the list returned. 

e.g. Searching for park causes the itinerarysolver to go through east coast park, fort canning park, etc.

I suggest either a pop up to fix the user's mistake or if that is not possible just return one String with the lowest lev distance.

**Comment by MatthewNeo** [comment]
Noted.

Do you want me to add the popup window?

**Comment by JulianJason** [comment]
Works like a charm @MatthewNeo 

Implemented
