### ISSUE TITLE
Scrollview Leak in aboutSG

### ISSUE THREAD

**Issue by JulianJason** [JulianJason/The-Travelling-Man#14]
There is a leak that can cause the phone to be very hot and causes a clash when you switch on tabs too fast.

Here is the relevant details

```java
 android.view.WindowLeaked: Activity com.lejit.thetravellingman.AboutSG has leaked window android.widget.ScrollView{fea8ae2 VFED.V.. ........ 0,0-800,1774} that was originally added here
```

I'm not sure how to tackle this, perhaps could take a look at detroying instances and unloading resources?

**Comment by imny94** [comment]
Yea, I got the same error as well... I think there might be too many images inside the activity. It couldn't run at first as well, until I set hardware acceleration= false, and largeheap = true. Might need to change the way the view is presented. This might be causing issues with the translation as well

**Comment by JulianJason** [comment]
Setting a large heap will only delay the problem. 
I saw Matt's commit on the ondestroy method. Lets just hope that it fixes this.

**Comment by JulianJason** [comment]
Fixed by dereferencing on OnDestroy
