### ISSUE TITLE
RSS feed activity doesn't seem to work on my Emulator

### ISSUE THREAD

**Issue by imny94** [JulianJason/The-Travelling-Man#6]
App crashes after leaving page open for a while. Might be due to some settings in my emulator though, not sure

**Comment by JulianJason** [comment]
Hi
Sorry I can't replicate this, It runs on my emulator.

Try to run this on the phone and see whether the rss works then report again.

Thanks

**Comment by imny94** [comment]
Need to update my gradle build, code works :)
